blog/urls.py
from django.urls import path
from . import views

#画像表示用
from django.contrib.auth import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'schedule'

urlpatterns = [
    #以下、本番用
    path('', views.CalView.as_view(), name='schedule'),
    path('<int:get_next_year>/<int:get_next_month>/', views.CalView.as_view(), name='next_m'),
    #path('move/<int:url_next_month>/', views.ScheduleView.as_view(), name='next'),
    #path('<int:url_previous_month>/', views.ScheduleView.as_view(), name='previous'),

    path('create/', views.ScheduleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ScheduleUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.ScheduleDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ScheduleDeleteView.as_view(), name='delete'),

    #複数変数の受け渡し方
    path('test/', views.TestView.as_view(), name='test'),
    path('test/<int:set1>/<int:set2>/', views.TestView.as_view(), name='test2'),

]

#画像表示用
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('challenge/', include('challenge.urls')),
    path('schedule/', include('blog.urls')),
    path('collect/', include('collect.urls')),
    path('menu/', include('menu.urls')),
    path('coin/', include('coin.urls')),
    path('chance/', include('chance.urls')),
]

register/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

#from register.views import AddPlayers

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

    path('add_player/', views.AddPlayers.as_view(), name='add_player' ),
    path('list_player/<int:pk>/', views.ListPlayers.as_view(), name='list_player' ),
    path('player_update/', views.PlayerUpdate.as_view(), name='player_update' ),
    path('player_edit/<int:pk>/', views.PlayerDetailUpdate.as_view(), name='player_edit' ),

]

register/models.py
from django.conf import settings
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager

# registerのUserモデルを使う場合だけ、登録する
if settings.AUTH_USER_MODEL == 'register.User':
    class UserManager(BaseUserManager):
        """ユーザーマネージャー"""
        use_in_migrations = True

        def _create_user(self, email, password, **extra_fields):
            """Create and save a user with the given username, email, and
            password."""
            if not email:
                raise ValueError('The given email must be set')
            email = self.normalize_email(email)

            user = self.model(email=email, **extra_fields)
            user.set_password(password)
            user.save(using=self._db)
            return user

        def create_user(self, email, password=None, **extra_fields):
            extra_fields.setdefault('is_staff', False)
            extra_fields.setdefault('is_superuser', False)
            return self._create_user(email, password, **extra_fields)

        def create_superuser(self, email, password, **extra_fields):
            extra_fields.setdefault('is_staff', True)
            extra_fields.setdefault('is_superuser', True)

            if extra_fields.get('is_staff') is not True:
                raise ValueError('Superuser must have is_staff=True.')
            if extra_fields.get('is_superuser') is not True:
                raise ValueError('Superuser must have is_superuser=True.')

            return self._create_user(email, password, **extra_fields)


    class User(AbstractBaseUser, PermissionsMixin):
        """カスタムユーザーモデル

        usernameを使わず、emailアドレスをユーザー名として使うようにしています。
        """
        email = models.EmailField(_('email address'), unique=True)
        first_name = models.CharField(_('first name'), max_length=30, blank=True)
        last_name = models.CharField(_('last name'), max_length=150, blank=True)
        user_flag = models.CharField(_('user flag'), max_length=150, blank=True)

        is_staff = models.BooleanField(
            _('staff status'),
            default=False,
            help_text=_(
                'Designates whether the user can log into this admin site.'),
        )
        is_active = models.BooleanField(
            _('active'),
            default=True,
            help_text=_(
                'Designates whether this user should be treated as active. '
                'Unselect this instead of deleting accounts.'
            ),
        )
        date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

        objects = UserManager()

        EMAIL_FIELD = 'email'
        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = []

        class Meta:
            verbose_name = _('user')
            verbose_name_plural = _('users')

        def get_full_name(self):
            """Return the first_name plus the last_name, with a space in
            between."""
            full_name = '%s %s' % (self.first_name, self.last_name)
            return full_name.strip()

        def get_short_name(self):
            """Return the short name for the user."""
            return self.first_name

        def email_user(self, subject, message, from_email=None, **kwargs):
            """Send an email to this user."""
            send_mail(subject, message, from_email, [self.email], **kwargs)

        @property
        def username(self):
            return self.email


class Player(models.Model):
    user_id = models.CharField(max_length=100)
    player_name = models.CharField(max_length=100)
    school_id = models.CharField(max_length=100)
    is_active = models.BooleanField(_('active'),
        default=True,help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'),)

    def publish(self):
        self.save()

    def __str__(self):
        return self.user_id

register/views.py
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm
)


User = get_user_model()


class Top(generic.TemplateView):
    template_name = 'register/top.html'

    #テンプレートに値を渡すにはcontextをオーバー
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #ログインユーザーのID表示
        context["foo"] = self.request.user.id
        context["foo_user"] = self.request.user
        #context["foo1"] = self.request.user.in_group

        #ユーザーグループの取得
        #グループ毎の処理を分岐させるにはget_context_dataをクラス毎に記載しておく
        if self.request.user.groups.filter(name='family').exists():
            context["foo1"] = 'family'
        elif self.request.user.groups.filter(name='coach').exists():
            context["foo1"] = 'coach'
        else:
            context["foo1"] = 'common'

        if self.request.user.id == None:
            context["foo"] = 0
        else:
            context["foo"] = 1

        return context


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('register/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('register/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoenNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # まだ仮登録で、他に問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()



class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スーパーユーザーだけユーザーページアクセスを許可する"""
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    """ユーザーの詳細ページ"""
    model = User
    template_name = 'register/user_detail.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    """ユーザー情報更新ページ"""
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'register/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/reset/subject.txt'
    email_template_name = 'register/mail_template/reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'


#以下追加機能--------------------------
#汎用ビューの書き方

from register.models import Player
from django.views.generic.edit import UpdateView

class ListPlayers(OnlyYouMixin, generic.ListView):
    """プレイヤーリスト表示ページ"""
    model = User
    context_object_name = "player_list"  # この行で変数名を指定
    #paginate_by = 5 #リストの件数

    def get_queryset(self, **kwargs):
        return Player.objects.filter(user_id=self.kwargs['pk']).order_by('id').reverse()

    template_name = 'register/user_list_player.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く


#登録していないと見せない（LoginRequiredMixin）
class AddPlayers(LoginRequiredMixin, generic.CreateView):
    template_name = 'register/user_add_player.html'
    model = Player
    fields = ("user_id","player_name",)

    #テンプレートに値を渡すにはcontextをオーバー
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #ログインユーザーのID表示
        context["foo"] = self.request.user.id
        context["foo1"] = self.request.user
        return context

    def get_success_url(self):
        return resolve_url('register:add_player')


class PlayerUpdate(OnlyYouMixin, generic.UpdateView):
    """これを消すとなぜかリストが表示できない"""
    template_name = 'register/top.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く


class PlayerDetailUpdate(UpdateView):
    """ユーザー情報更新ページ"""
    model = Player
    fields = ("player_name", "is_active", )
    #form_class = UserUpdateForm
    template_name = 'register/user_update_player.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く

    def get_success_url(self):
        return resolve_url('register:top')

register/templates/register/base.html
{% load static %}

<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap&subset=japanese" rel="stylesheet">


    <title>Alpacca System</title>
  </head>
  <body>
      <div class="wrapper">

      <!-- ナビバー -->
      <div class="page-header">
      <nav class="navbar">
        <a class="navbar-brand" href="{% url 'register:top' %}"><img src="{% static 'img/alpacca.png' %}" width="180px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          +
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li>
              <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">ユーザー情報閲覧</a>
            </li>
            <li>
              <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
            </li>

            <li>
              <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
            </li>
            <li>
              <a class="nav-item nav-link" href="{% url 'register:password_change' %}">パスワードの変更</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-item nav-link" href="{% url 'register:login' %}">
              ようこそ、ゲスト！ログインはこちら
            </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
  </div>


      <div class="container">
              {% block content %}
              {% endblock %}
      </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

register/templates/register/login.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <!-- 左側、ログインエリア -->

        <div  class="main_box3">
        <form action="{% url 'register:login' %}" method="POST">
            {{ form.non_field_errors }}
            {% for field in form %}
                <div class="regi_form">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <div class="regi_form2">
                <button type="submit" class="btn btn-info btn-lg btn-block" >ログイン</button>
            </div>
            <input type="hidden" name="next" value="{{ next }}" />
            {% csrf_token %}
        </form>
        </div>

    </div><!-- 左側、ログインエリアおわり -->

    <!-- 右側、会員登録エリア -->

        <div class="regi_form2">
            <a href="{% url 'register:user_create' %}" class="btn btn-info btn-lg btn-block" >会員登録</a>
        </div>
        <div class="regi_form2">
            <a href="{% url 'register:password_reset' %}" class="btn btn-info btn-lg btn-block" >パスワードを忘れた方</a>
        </div>

</div>
{% endblock %}

register/templates/register/password_change.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="main_box3">

<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="regi_form">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <div class="regi_form2">
        <button type="submit" class="btn btn-info">送信</button>
    </div>
</form>

</div>
</div>
</div>

{% endblock %}

register/templates/register/password_change_done.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="main_box3">

    <div class="regi_form">
        パスワードを変更しました。<br>
    </div>
    <div class="regi_form2">
        <a class="btn btn-info" href="{% url 'register:login' %}">ログイン</a>
    </div>

</div>
</div>
</div>

{% endblock %}

register/templates/register/password_reset_confirm.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="gt_box1">

<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-info">送信</button>
</form>

</div>
</div>
</div>

{% endblock %}

register/templates/register/password_reset_done.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="gt_box1">

    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。

</div>
</div>
</div>

{% endblock %}

register/templates/register/password_reset_form.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="main_box3">

<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="regi_form">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <div class="regi_form2">
        <button type="submit" class="btn btn-info">送信</button>
    </div>
</form>

</div>
</div>
</div>

{% endblock %}

register/templates/register/top.html
{% extends "register/base.html" %}
{% block content %}

<script type="text/javascript" language="javascript">
    var login_flag =  {{ foo }};
    window.onload = function() {
        document.getElementById("incomplete").style.display="none";
        if(login_flag == 0){
            document.getElementById("incomplete").style.display="block";
        } else {
            document.getElementById("completion").style.display="block";
        }
    }
    function onButtonClick1() {
        if(login_flag == 0){
            document.getElementById("incomplete").style.display="block";
        } else {
            document.getElementById("completion").style.display="block";
        }
    }
</script>

<div class="container">
    <div class="row">

            {% if foo1 == 'family' %}

            <div class="col-xs-6">
                <div class="box_set1">
                    <a class="btn-circle-stitch2" href="/challenge" role="button">Ten thousand challenge</a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="box_set1">
                    <a class="btn-circle-stitch" href="/schedule" role="button">Schedule</a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="box_set1">
                    <a class="btn-circle-stitch" href="/menu" role="button">Menu</a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="box_set1">
                    <a class="btn-circle-stitch2" href="/chance" role="button">Chance of shot</a>
                </div>
            </div>
            {% else %}
                <div class="box_set2">
                    <a class="btn-circle-stitch" href="/schedule" role="button">Schedule</a>
                </div>

            {% endif %}
    </div>
</div>

<div>
    　<br><br><br><br><br><br>
</div>

<footer class="footer">

    <div  class="user_box">

        こんにちわ {{ foo_user }}さん

        <div style="text-align:center; font-size:80%; ">グループ：{{ foo1 }}</div>

    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>

</footer>

{% endblock %}

register/templates/register/user_add_player.html
{% extends "register/base.html" %}
{% block content %}

 <script type="text/javascript" language="javascript">
    window.onload = function() {
        target = document.getElementById("id_user_id");
        target.value = {{ foo }};
        document.getElementById("id_user_id").style.display="none";
        document.getElementById("User id").style.display="none";
        
        target = document.getElementById("id_user_id");
        target.innerHTML = "Penguin";
        
    };
    function onButtonClick1() {
          target = document.getElementById("id_server");
          target.value = 'player';
     }
 </script>

<div class="row o-3column">
<div class="col-md-12">
<div  class="gt_box1">

<form action="" method="POST">
    {{ form.non_field_errors }}
    {{ form.user_id }}
    <table class="table">
        <tbody>
            <tr>
                <th><label for="id_player_name">プレイヤー名</label></th>
                <td>{{ form.player_name }}</td>
            </tr>
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-info" >追加</button>
</form>

</div>
</div>
</div>

{% endblock %}

register/templates/register/user_create.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="main_box3">

<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="regi_form">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <div class="regi_form2">
        <button type="submit" class="btn btn-info">送信</button>
    </div>
</form>

</div>
</div>
</div>

{% endblock %}

register/templates/register/user_create_complete.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="gt_box1">

    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-info" href="{% url 'register:login' %}">ログイン</a>

</div>
</div>
</div>

{% endblock %}

register/templates/register/user_detail.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="main_box3">
    <div class="regi_txt">
        ユーザーネーム：{{ user.username }}
    </div>
    <div class="regi_txt">
        氏名：{{ user.first_name }}　{{ user.last_name }}
    </div>
    <div class="regi_txt">
        {% if user.username != user.email %}
            メールアドレス：{{ user.email }}
        {% endif %}
    </div>

</div>
</div>
</div>

<div  class="main_box2">
    　
</div>

{% endblock %}

register/templates/register/user_form.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="main_box3">

<form action="" method="POST">
    {{ form.non_field_errors }}

    {% for field in form %}
    <div class="regi_form">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }} {{ field.errors }}
    </div>
    {% endfor %}


    {% csrf_token %}
    <div class="regi_form2">
        <button type="submit" class="btn btn-info" >更新</button>
    </div>
</form>

</div>
</div>
</div>

{% endblock %}

register/templates/register/user_update_player.html
{% extends "register/base.html" %}
{% block content %}

<div class="row o-3column">
<div class="col-md-12">
<div  class="gt_box1">

<form method="post">
    {% csrf_token %}
    <table class="table">
        {{ form }}
    </table>
    <input type="submit" class="btn btn-info" >
</form>

<br />

    <div class="card col-md-6">
    チェックボックスを外して、そのユーザーを非アクティブにするとプレイヤーリストに
    表示されなくなります。そのプレイヤーが削除された状態になってしまいますので、
    ご注意ください。

    </div>


</div>
</div>
</div>



{% endblock %}