blog/urls.py
from django.urls import path
from . import views

#画像表示用
from django.contrib.auth import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'schedule'

urlpatterns = [
    #以下、本番用
    path('', views.CalView.as_view(), name='schedule'),
    path('<int:get_next_year>/<int:get_next_month>/', views.CalView.as_view(), name='next_m'),
    #path('move/<int:url_next_month>/', views.ScheduleView.as_view(), name='next'),
    #path('<int:url_previous_month>/', views.ScheduleView.as_view(), name='previous'),

    path('create/', views.ScheduleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ScheduleUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.ScheduleDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ScheduleDeleteView.as_view(), name='delete'),

    #複数変数の受け渡し方
    path('test/', views.TestView.as_view(), name='test'),
    path('test/<int:set1>/<int:set2>/', views.TestView.as_view(), name='test2'),

]

#画像表示用
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('challenge/', include('challenge.urls')),
    path('schedule/', include('blog.urls')),
    path('collect/', include('collect.urls')),
    path('menu/', include('menu.urls')),
    path('coin/', include('coin.urls')),
    path('chance/', include('chance.urls')),
]

register/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

#from register.views import AddPlayers

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

    path('add_player/', views.AddPlayers.as_view(), name='add_player' ),
    path('list_player/<int:pk>/', views.ListPlayers.as_view(), name='list_player' ),
    path('player_update/', views.PlayerUpdate.as_view(), name='player_update' ),
    path('player_edit/<int:pk>/', views.PlayerDetailUpdate.as_view(), name='player_edit' ),

]

scheduler/urls.py
from django.urls import path
from . import views


app_name = 'scheduler'

urlpatterns = [
    path('', views.AlpaccaCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path(
        'week_with_schedule/<int:year>/<int:month>/<int:day>/',
        views.WeekWithScheduleCalendar.as_view(),
        name='week_with_schedule'
    ),
    path(
        'month_with_schedule/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path(
        'month_with_schedule/<int:year>/<int:month>/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),
    path(
        'month_with_forms/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
    path(
        'month_with_forms/<int:year>/<int:month>/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    show_flag = models.CharField('表示フラグ', max_length=50, default=1)
    reservation_flag = models.CharField('予約フラグ', max_length=50, default=1)
    #start_time = models.TimeField('開始時間', default=timezone.now)
    start_time = models.TimeField('開始時間', default='09:00')
    end_time = models.TimeField('終了時間', default='10:00')
    date = models.DateField('日付', default=timezone.now)

    created_date = models.DateTimeField(
            default=timezone.now)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

import bootstrap_datepicker_plus as datetimepicker





class BlogForm(forms.ModelForm):

    CHOICE_1 = (
        ('1', '家族のみ'),
        ('2', '全員表示'),
    )
    CHOICE_2 = (
        ('1', '要予約'),
        ('2', '予約済'),
    )

    """定数リストによるプルダウンメニュー"""
    show_flag = forms.ChoiceField(widget=forms.Select, choices=CHOICE_1)
    reservation_flag = forms.ChoiceField(widget=forms.Select, choices=CHOICE_2)
    #入力フォームを日付と時間に分割する場合
    #start_time = forms.SplitDateTimeField(label='開始時間')

    class Meta:
        model = Post
        fields = ('author', 'title', 'text', 'show_flag', 'reservation_flag', 'start_time', 'end_time', 'date',)
        #fields = '__all__'
        widgets = {
            'date': datetimepicker.DatePickerInput(
                format='%Y-%m-%d',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }
            ),
            'start_time': datetimepicker.TimePickerInput(
                format='%H:%M',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }

            ),
            'end_time': datetimepicker.TimePickerInput(
                format='%H:%M',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }
            ),
        }




class BlogFormEdit(forms.ModelForm):

    CHOICE_1 = (
        ('1', '家族のみ'),
        ('2', '全員表示'),
    )
    CHOICE_2 = (
        ('1', '要予約'),
        ('2', '予約済'),
    )

    """定数リストによるプルダウンメニュー"""
    #show_flag = forms.ChoiceField(widget=forms.Select, choices=CHOICE_1)
    reservation_flag = forms.ChoiceField(widget=forms.Select, choices=CHOICE_2)
    #入力フォームを日付と時間に分割する場合
    #start_time = forms.SplitDateTimeField(label='開始時間')

    class Meta:
        model = Post
        fields = ('title', 'text', 'reservation_flag', 'start_time', 'end_time', 'date', )
        #fields = '__all__'
        widgets = {
            'date': datetimepicker.DatePickerInput(
                format='%Y-%m-%d',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }
            ),
            'start_time': datetimepicker.TimePickerInput(
                format='%H:%M',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }

            ),
            'end_time': datetimepicker.TimePickerInput(
                format='%H:%M',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }
            ),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect, resolve_url
import datetime
from django.views.generic import (
    TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView,
)
from .models import Post
from challenge.models import Post10
from . import mixins
from django.utils import timezone

#会員情報関連
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
User = get_user_model()

#dataFrameの利用に必要
from django_pandas.io import read_frame

from .forms import (
    BlogForm, BlogFormEdit,
)

import calendar
from django.utils import timezone

now = timezone.localtime(timezone.now())


#非ログイン対応
class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スタッフユーザーだけアクセスを許可する"""
    raise_exception = False

    def test_func(self):
        user = self.request.user
        #return user.is_superuser
        return user.is_staff


#メイン表示
class CalView(OnlyYouMixin, mixins.WeekWithScheduleMixin, TemplateView):
    model = Post
    template_name = "blog/cal.html"
    now = timezone.localtime(timezone.now())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #曜日情報の取得
        cal = calendar.Calendar(firstweekday=6)


        context["defailt_year"] = self.now.year
        context["defailt_month"] = self.now.month

        context["next_month"] = 0

        dic_next = {}
        dic_next["year"] = self.now.year
        dic_next["month"] = self.now.month

        if self.kwargs.get('get_next_month') is None:
            context["pre_year"] = context["defailt_year"]
            context["pre_month"] = context["defailt_month"] - 1
            context["next_year"] = context["defailt_year"]
            context["next_month"] = context["defailt_month"] + 1
            context["view_month"] = self.now.month

            #曜日情報の取得
            context["calendar"] = cal.itermonthdays2(self.now.year, self.now.month)
        #次月処理
        else:
            context["view_month"] = self.kwargs.get('get_next_month')
            context["next_year"] = self.kwargs.get('get_next_year')
            context["next_month"] = self.kwargs.get('get_next_month') + 1
            dic_next["year"] = self.kwargs.get('get_next_year')
            dic_next["month"] = self.kwargs.get('get_next_month')

            if context["next_month"] == 14:
                context["next_month"] = 1
                dic_next["month"] = 1
                context["view_month"] = 1
                context["next_year"] = context["next_year"] + 1

            #曜日情報の取得
            context["calendar"] = cal.itermonthdays2(context["next_year"], dic_next["month"])

        #ユーザーグループの取得
        #グループ毎の処理を分岐させるにはget_context_dataをクラス毎に記載しておく
        if self.request.user.groups.filter(name='family').exists():
            context["foo1"] = 'family'
            context["week"] = Post.objects.order_by('created_date').reverse().filter(date__year=dic_next["year"], date__month=dic_next["month"])
        elif self.request.user.groups.filter(name='coach').exists():
            context["foo1"] = 'coach'
            context["week"] = Post.objects.order_by('created_date').reverse().filter(date__year=dic_next["year"], date__month=dic_next["month"])
        else:
            context["foo1"] = 'common'
            context["week"] = Post.objects.order_by('created_date').reverse().filter(show_flag='2').filter(date__year=dic_next["year"], date__month=dic_next["month"])

        #日付情報の取得
        context["now"] = self.now

        return context


#受け渡しテスト
class TestView(OnlyYouMixin, TemplateView):
    model = Post
    template_name = "blog/test.html"
    now = timezone.localtime(timezone.now())
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["foo"] = self.now.year
        context["foo2"] = self.now.month
        #初期値
        context["get1"] = 1000

        if context["get1"] is 1000:
            context["get1"] = self.now.month
        else:
            context["get1"] = self.kwargs.get('set1') + 1

        return context



#詳細表示
class ScheduleDetailView(OnlyYouMixin, DetailView):
    model = Post
    template_name = "blog/detail.html"


#エントリーフォーム
class ScheduleCreateView(OnlyYouMixin, CreateView):
    model = Post
    template_name = "blog/blog_new.html"
    form_class = BlogForm

    def get_success_url(self):
        return resolve_url('schedule:schedule')


#投稿内容の編集
class ScheduleUpdateView(OnlyYouMixin, UpdateView):
    model = Post
    template_name = "blog/blog_edit.html"
    form_class = BlogFormEdit

    def get_success_url(self):
        return resolve_url('schedule:schedule')


#投稿の削除
class ScheduleDeleteView(OnlyYouMixin, DeleteView):
    model = Post
    template_name = "blog/blog_delete.html"

    def get_success_url(self):
        return resolve_url('schedule:schedule')

blog/templates/blog/base.html
{% load static %}

<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap&subset=japanese" rel="stylesheet">


    <!--カレンダー入力-->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>






<title>Schedule</title>
  </head>
  <body>
      <div class="wrapper">
      <div class="page-header">
          <div class="page_title">
          <a class="navbar-brand" href="{% url 'register:top' %}"><img src="{% static 'img/alpacca.png' %}" width="150px"></a>
        </div>
      </div>

      <div class="page-header2">
          <div class="page_title">

          <h1><a href="/schedule">Schedule</a></h1>
        </div>
      </div>
      <div class="container">
              {% block content %}
              {% endblock %}
      </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>

  </body>
</html>

blog/templates/blog/cal.html
{% extends 'blog/base.html' %}
{% block content %}


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="main_box3">
        {{ next_year }}：{{ view_month }}月の予定
    </div>
</div>

<div class="month_console">
    <div class="month_controller">
        {% if foo1 == 'family' %}
            <a href="{% url 'schedule:create' %}" >+ Add New</a>
        {% endif %}
    </div>
    <div class="month_controller">
        <a href="/schedule">Current</a>：
        <a href="{% url 'schedule:next_m' next_year next_month %}">Next</a>
    </div>
</div>




<table class="table table-striped">

{% for item in calendar %}
    {% if item.0 != 0 %}
        <tr>
        <td>
        <nobr>

        <!-- 曜日を記載変換 -->
        {% if item.1 == 0 %}
            <div class="weak_1">Mon</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 1 %}
            <div class="weak_1">Tue</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 2 %}
            <div class="weak_1">Wed</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 3 %}
            <div class="weak_1">Thu</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 4 %}
            <div class="weak_1">Fri</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 5 %}
            <div class="weak_2">Sat</div>
            <div class="mid_2"><br>{{item.0}}</div>
        {% elif item.1 == 6 %}
            <div class="weak_3">Sun</div>
            <div class="mid_3"><br>{{item.0}}</div>
        {% endif %}
        </nobr>
        </td>
        <td>

        {% for new_week in week %}
            {% if new_week.date.day == item.0 %}
                {% if new_week.show_flag == '1' %}
                    <div class="schedule_box_1_b">
                {% else %}
                    <div class="schedule_box_1_a">
                {% endif %}
                <div class="schedule_box_2">
                    <a href="{% url 'schedule:update' new_week.pk %}">{{ new_week.title }}</a>
                </div>
                <div class="schedule_box_3">
                    {{ new_week.text | linebreaksbr }}
                </div>

                <div class="schedule_box_4">

                    <div class="schedule_box_5">

                        {% if new_week.reservation_flag == '1' %}
                            <div class="big_1">要予約</div>
                        {% else %}
                            <div class="big_2">予約済</div>
                        {% endif %}
                    </div>

                    <div class="schedule_box_6">
                        {{ new_week.start_time }}〜{{ new_week.end_time }}
                    </div>

                    {% if foo1 == 'family' %}
                    <div class="schedule_box_6">
                        ｜<a href="{% url 'schedule:delete' new_week.pk %}">予定の削除</a>
                    </div>
                    {% endif %}

                <br>

                </div>

            {% endif %}
        {% endfor %}
        </td>
        </tr>

    {% endif %}
{% endfor %}

</table>





<div class="now_box">
{{ now.year }}年
{{ now.month }}月
{{ now.day }}日
{{ now.hour }}時
{{ now.minute }}分
{{ now.second }}秒
</div>

<br><br>

<footer>

    <div class="month_console">
        <div class="month_controller">
            {% if foo1 == 'family' %}
            <a href="{% url 'schedule:create' %}" >+ Add New</a>
            {% endif %}
        </div>
        <div class="month_controller">
            <a href="{% url 'schedule:next_m' next_year next_month %}">Next</a>
        </div>
    </div>

    <div  class="user_box">
        <p>ユーザー属性：{{ foo1 }} </p>
    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>

</footer>


{% endblock %}

blog/templates/blog/schedule.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="main_box3">
        {{ next }}月の予定
    </div>
</div>


<div class="month_console">
    <div class="month_controller">
        {% if foo1 == 'family' %}
        <a href="{% url 'schedule:create' %}" >+ Add New</a>
        {% endif %}
    </div>
    <div class="month_controller">
        <a href="{% url 'schedule:next' next %}">Next</a>
    </div>
</div>



<table class="table table-striped">


{% for item in calendar %}
    {% if item.0 != 0 %}
        <tr>
        <td>
        <nobr>

        <!-- 曜日を記載変換 -->
        {% if item.1 == 0 %}
            <div class="weak_1">Mon</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 1 %}
            <div class="weak_1">Tue</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 2 %}
            <div class="weak_1">Wed</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 3 %}
            <div class="weak_1">Thu</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 4 %}
            <div class="weak_1">Fri</div>
            <div class="mid_1"><br>{{item.0}}</div>
        {% elif item.1 == 5 %}
            <div class="weak_2">Sat</div>
            <div class="mid_2"><br>{{item.0}}</div>
        {% elif item.1 == 6 %}
            <div class="weak_3">Sun</div>
            <div class="mid_3"><br>{{item.0}}</div>
        {% endif %}
        </nobr>
        </td>
        <td>

        {% for new_week in week %}
            {% if new_week.date.day == item.0 %}
                {% if new_week.show_flag == '1' %}
                    <div class="schedule_box_1_b">
                {% else %}
                    <div class="schedule_box_1_a">
                {% endif %}
                <div class="schedule_box_2">
                    <a href="{% url 'schedule:update' new_week.pk %}">タイトル：{{ new_week.title }}</a>
                </div>
                <div class="schedule_box_3">
                    {{ new_week.text }}
                </div>

                <div class="schedule_box_4">

                    <div class="schedule_box_5">

                        {% if new_week.reservation_flag == '1' %}
                            <div class="big_1">要予約</div>
                        {% else %}
                            <div class="big_2">予約済</div>
                        {% endif %}
                    </div>

                    <div class="schedule_box_6">
                        {{ new_week.start_time }}〜{{ new_week.end_time }}
                    </div>

                <br>

                </div>

            {% endif %}
        {% endfor %}
        </td>
        </tr>

    {% endif %}
{% endfor %}

</table>

<br>

<div class="now_box">
{{ now.year }}年
{{ now.month }}月
{{ now.day }}日
{{ now.hour }}時
{{ now.minute }}分
{{ now.second }}秒
</div>

<br><br>

<footer>

    <div class="month_console">
        <div class="month_controller">
            {% if foo1 == 'family' %}
            <a href="{% url 'schedule:create' %}" >+ Add New</a>
            {% endif %}
        </div>
        <div class="month_controller">
            <a href="{% url 'schedule:next' next %}">Next</a>
        </div>
    </div>

    <div  class="user_box">
        <p>ユーザー属性：{{ foo1 }} </p>
    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>

</footer>

{% endblock %}

blog/templates/blog/test.html
{% extends 'challenge/base.html' %}

{% block content %}


テスト
{{ foo }}：{{ foo2 }}
<br />
<a href="{% url 'schedule:test2' foo foo2 %}">Next10</a>

<br />

{{ get1 }}



{% endblock %}

blog/templates/blog/week.html
{% extends 'blog/base.html' %}
{% block content %}

年：{{ now.year }}
月：{{ now.month }}
日：{{ now.day }}
時：{{ now.hour }}
分：{{ now.minute }}
秒：{{ now.second }}
<br><hr><br>

    <a href="{% url 'scheduler:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'scheduler:week_with_schedule' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table table-bordered">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for schedules in week_day_schedules.values %}
                <td>
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.summary }}<br>
                        {{ s.show_flag }}<br>
                        {{ s.description | linebreaks }}
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>




    <table class="table table-bordered">
        <tbody>
        {% for week_name, day, schedules in week_row %}
            <tr>
                <td>
                    {% if week_first.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}
                    ({{ week_name }})<br><br>

                    {% for s in schedules %}
                        {% if s.date.day == day.day %}

                            大本：{{ day.day }}<br>
                            投稿：{{ s.date.day }}<br>

                            {{ s.start_time }} - {{ s.end_time }}<br>
                            {{ s.title }}<br>
                            {{ s.text }}<br>
                            {{ s.description | linebreaks }}<br>
                            {{ s.show_flag }}<br>
                            {{ s.reservation_flag }}
                            {% if s.reservation_flag == '1' %}
                                未予約
                            {% else %}
                                予約済
                            {% endif %}<br>
                            参照日付：{{ s.date }}
                        {% endif %}
                    {% endfor %}
                </td>

                <td>
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.title }}<br>
                        {{ s.text }}<br>
                        {{ s.description | linebreaks }}<br>
                        {{ s.show_flag }}<br>
                        {{ s.reservation_flag }}
                        {% if s.reservation_flag == '1' %}
                            未予約
                        {% else %}
                            予約済
                        {% endif %}<br>
                        参照日付：{{ s.date }}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>




{% endblock %}