blog/urls.py
from django.urls import path
from . import views

#画像表示用
from django.contrib.auth import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'schedule'

urlpatterns = [
    #以下、本番用
    path('', views.CalView.as_view(), name='schedule'),
    path('<int:get_next_year>/<int:get_next_month>/', views.CalView.as_view(), name='next_m'),
    #path('move/<int:url_next_month>/', views.ScheduleView.as_view(), name='next'),
    #path('<int:url_previous_month>/', views.ScheduleView.as_view(), name='previous'),

    path('create/', views.ScheduleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ScheduleUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.ScheduleDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ScheduleDeleteView.as_view(), name='delete'),

    #複数変数の受け渡し方
    path('test/', views.TestView.as_view(), name='test'),
    path('test/<int:set1>/<int:set2>/', views.TestView.as_view(), name='test2'),

]

#画像表示用
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chance/urls.py
from django.urls import path
from . import views

#画像表示用
from django.contrib.auth import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'chance'

urlpatterns = [
    #以下、本番用
    path('', views.MainView.as_view(), name='chance'),

    path('new_match', views.MatchCreateView.as_view(), name='new_match'),
    path('match_view/<int:pass_id>/', views.MatchView.as_view(), name='match_view'),
    path('match_detail/<int:pk>/', views.MatchDetailView.as_view(), name='match_detail'),
    path('delete/<int:pk>/', views.MatchDeleteView.as_view(), name='match_delete'),

    #path('', views.index, name='index'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('challenge/', include('challenge.urls')),
    path('schedule/', include('blog.urls')),
    path('collect/', include('collect.urls')),
    path('menu/', include('menu.urls')),
    path('coin/', include('coin.urls')),
    path('chance/', include('chance.urls')),
]

register/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

#from register.views import AddPlayers

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

    path('add_player/', views.AddPlayers.as_view(), name='add_player' ),
    path('list_player/<int:pk>/', views.ListPlayers.as_view(), name='list_player' ),
    path('player_update/', views.PlayerUpdate.as_view(), name='player_update' ),
    path('player_edit/<int:pk>/', views.PlayerDetailUpdate.as_view(), name='player_edit' ),

]

chance/models.py
from django.db import models
from django.utils import timezone


class CMatch(models.Model):
    player = models.CharField(max_length=100, default='大凱')
    opponent = models.CharField(max_length=100, default='対戦相手')
    created_date = models.DateTimeField(default=timezone.now)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.created_date.strftime("%Y/%m/%d %H:%M:%S")


class CGame(models.Model):
    game_id = models.CharField(max_length=200, default=1)
    stroke = models.IntegerField(max_length=100, default=0)
    stroke_error = models.IntegerField(max_length=100, default=0)
    service = models.IntegerField(max_length=100, default=0)
    service_error = models.IntegerField(max_length=100, default=0)
    second = models.IntegerField(max_length=100, default=0)
    second_error = models.IntegerField(max_length=100, default=0)
    receive = models.IntegerField(max_length=100, default=0)
    receive_error = models.IntegerField(max_length=100, default=0)
    net = models.IntegerField(max_length=100, default=0)
    net_error = models.IntegerField(max_length=100, default=0)
    games = models.CharField(max_length=100, default=0)
    created_date = models.DateTimeField(default=timezone.now)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.game_id

chance/forms.py
from django import forms
from .models import CMatch
from .models import CGame

import bootstrap_datepicker_plus as datetimepicker


class MatchForm(forms.ModelForm):

    CHOICE_1 = (
        ('大凱', '大凱'),
        ('剛生', '剛生'),
    )
    CHOICE_2 = (
        ('1', 'Win'),
        ('2', 'Lose'),
    )

    """定数リストによるプルダウンメニュー"""
    #player = forms.ChoiceField(widget=forms.Select, choices=CHOICE_1)

    class Meta:
        model = CMatch
        fields = ('player', 'opponent', 'created_date',)
        #fields = '__all__'


class GameForm(forms.ModelForm):

    # bootstarap4
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


    CHOICE_1 = (
        ('大凱', '大凱'),
        ('剛生', '剛生'),
    )
    CHOICE_2 = (
        ('1', 'Win'),
        ('2', 'Lose'),
    )

    """定数リストによるプルダウンメニュー"""
    games = forms.ChoiceField(widget=forms.Select, choices=CHOICE_2)

    class Meta:
        model = CGame
        fields = ('game_id', 'stroke', 'stroke_error', 'service', 'service_error', 'second', 'second_error', 'receive', 'receive_error', 'net', 'net_error', 'games', 'created_date',)
        #fields = '__all__'

chance/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect, resolve_url
from django.http import HttpResponse
from django.views.generic import (
    TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView,
)
from .models import CMatch
from .models import CGame
from django.utils import timezone
now = timezone.localtime(timezone.now())

#会員情報関連
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
User = get_user_model()

#dataFrameの利用に必要
from django_pandas.io import read_frame

#ページネーション
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import (
    MatchForm, GameForm,
)


#非ログイン対応
class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スタッフユーザーだけアクセスを許可する"""
    raise_exception = False

    def test_func(self):
        user = self.request.user
        #return user.is_superuser
        return user.is_staff


#メイン画面
class MainView(OnlyYouMixin, ListView):
    model = CMatch
    template_name = "chance/index.html"
    now = timezone.localtime(timezone.now())
    queryset = CMatch.objects.order_by('-created_date')
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = self.now
        context["foo"] = 10

        return context



#試合登録フォーム
class MatchCreateView(OnlyYouMixin, CreateView):
    model = CMatch
    template_name = "chance/match_new.html"
    form_class = MatchForm

    def get_success_url(self):
        #最新の登録IDを取得して、データ登録時のIDとして利用
        set = CMatch.objects.all().last()
        pass_id = set.id
        return resolve_url('chance:match_view' ,pass_id)


#試合詳細
class MatchView(OnlyYouMixin, CreateView):
    model = CMatch
    template_name = "chance/match_view.html"
    form_class = GameForm
    now = timezone.localtime(timezone.now())
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["game_count1"] = 0
        context["game_count2"] = 0

        #試合登録で取得したID情報を受け取り
        context["pass_id"] = self.kwargs.get('pass_id')
        over_id = self.kwargs.get('pass_id')
        set = CMatch.objects.get(id = over_id)

        #当該試合のゲーム数をカウント
        show_game = CGame.objects.filter(game_id = over_id)
        if show_game.first() is not None:
            df = read_frame(show_game)
            df_game_count1 = df[df.games == '1']
            df_game_count2 = df[df.games == '2']
            df_game_count1 = len(df_game_count1)
            df_game_count2 = len(df_game_count2)

            context["game_count1"] = df_game_count1
            context["game_count2"] = df_game_count2

            #成功率の算出
            context["probability_stroke"] = 100 - (df["stroke_error"].sum() / df["stroke"].sum() * 100)
            context["probability_service"] = 100 - (df["service_error"].sum() / df["service"].sum() * 100)
            context["probability_second"] = 100 - (df["second_error"].sum() / df["second"].sum() * 100)
            context["probability_receive"] = 100 - (df["receive_error"].sum() / df["receive"].sum() * 100)
            context["probability_net"] = 100 - (df["net_error"].sum() / df["net"].sum() * 100)

        context["player"] = set.player
        context["opponent"] = set.opponent
        context["created_date"] = set.created_date

        context['form'] = GameForm( initial = { 'game_id':over_id } )

        return context

    def get_success_url(self):
        over_id = self.kwargs.get('pass_id')
        return resolve_url('chance:match_view', over_id)



#試合詳細表示ーー
class MatchDetailView(OnlyYouMixin, UpdateView):

    model = CMatch
    template_name = "chance/match_detail.html"
    form_class = MatchForm
    now = timezone.localtime(timezone.now())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = self.now

        #遷移元の引数を確認
        over_id = self.kwargs['pk']
        #当該ゲーム情報
        #set = CMatch.objects.all().filter(pk = over_id)
        set = CMatch.objects.get(pk = over_id)
        context["foo"] = set.player

        #当該試合のゲーム数をカウント
        show_game = CGame.objects.filter(game_id = over_id)
        df = read_frame(show_game)


        df_game_count1 = df[df.games == '1']
        df_game_count2 = df[df.games == '2']
        df_game_count1 = len(df_game_count1)
        df_game_count2 = len(df_game_count2)

        context["player"] = set.player
        context["opponent"] = set.opponent
        context["created_date"] = set.created_date
        context["game_count1"] = df_game_count1
        context["game_count2"] = df_game_count2

        #成功率の算出
        context["probability_stroke"] = 100 - (df["stroke_error"].sum() / df["stroke"].sum() * 100)
        context["probability_service"] = 100 - (df["service_error"].sum() / df["service"].sum() * 100)
        context["probability_second"] = 100 - (df["second_error"].sum() / df["second"].sum() * 100)
        context["probability_receive"] = 100 - (df["receive_error"].sum() / df["receive"].sum() * 100)
        context["probability_net"] = 100 - (df["net_error"].sum() / df["net"].sum() * 100)
        #本数
        context["all_stroke"] = df["stroke"].sum()
        context["all_service"] = df["service"].sum()
        context["all_second"] = df["second"].sum()
        context["all_receive"] = df["receive"].sum()
        context["all_net"] = df["net"].sum()
        context["all_stroke_error"] = df["stroke_error"].sum()
        context["all_service_error"] = df["service_error"].sum()
        context["all_second_error"] = df["second_error"].sum()
        context["all_receive_error"] = df["receive_error"].sum()
        context["all_net_error"] = df["net_error"].sum()

        return context

    def get_success_url(self):
        return resolve_url('chance:chance')



#投稿の削除
class MatchDeleteView(OnlyYouMixin, DeleteView):
    model = CMatch
    template_name = "chance/match_delete.html"

    def get_success_url(self):
        return resolve_url('chance:chance')

chance/templates/chance/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/menu_style.css' %}">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap&subset=japanese" rel="stylesheet">
        <title>menu</title>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <div class="page-header">
                <div class="page_title">
                    <a class="navbar-brand" href="{% url 'register:top' %}"><img src="{% static 'img/alpacca.png' %}" width="150px"></a>
                </div>
            </div>
            <div class="page-header2">
                <div class="page_title">
                    <h1><a href="/chance">Chance of shot</a></h1>
                </div>
            </div>
            <div class="container">

            {% block content %}
            {% endblock %}

            </div>
        </div>
    </body>
</html>

chance/templates/chance/index.html
{% extends 'chance/base.html' %}

{% block content %}


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="main_box">
        Match History　<a class="form_b_03" href="{% url 'chance:new_match' %}" role="button">新規登録</a>
    </div>


    <table class="table table-striped">
        {% for post in object_list %}
        <tr>
            <td>
                <div class="weak_1">{{ post.created_date }}</div>
                <a href="{% url 'chance:match_detail' post.pk %}"><i class="fas fa-info-circle" style="color: #e172a9;"></i>{{ post.player }} vs {{ post.opponent }}</a>
                <a href="{% url 'chance:match_delete' post.pk %}">　<i class="fas fa-trash-alt" style="color: #197ab2;"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>

</div>


<div class="mid_box_page">
    <nav aria-label="ページネーション">
    	<ul class="pagination">

    		{% if page_obj.has_previous %}
    			<li class="page-item">
    				<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="前へ">
    					<i class="fas fa-chevron-circle-left"></i> Prev
    				</a>
    			</li>
    		{% endif %}

    		{% for page_num in page_obj.paginator.page_range %}
    			{% if page_num == page_obj.number %}
    				<li class="page-item active">
    					<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    				</li>
    			{% else %}
    				<li class="page-item">
    					<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    				</li>
    			{% endif %}
    		{% endfor %}

    		{% if page_obj.has_next %}
    			<li class="page-item">
    				<a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="次へ">
    					Next <i class="fas fa-chevron-circle-right"></i>
    				</a>
    			</li>
    		{% endif %}

    	</ul>
    </nav>
</div>



<footer>
    <div  class="user_box">

        <div style="text-align:center; font-size:80%; ">
            <div class="weak_5">
            {{ now.year }}年
            {{ now.month }}月
            {{ now.day }}日
            {{ now.hour }}時
            {{ now.minute }}分
            {{ now.second }}秒
            </div>
        </div>
    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>
</footer>


{% endblock %}

chance/templates/chance/match_delete.html
{% extends 'chance/base.html' %}

{% block content %}


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="main_box">
        Match Delete
    </div>

    <div class="mid_box">
        <div class="weak_1">{{ created_date }}</div>

            <form method="POST" class="post-form">{% csrf_token %}
                <br><br>
                本当に結果を削除しても構いませんか？<br><br><br>
                {{ form.as_p }}
                <button type="submit" class="form_b_01">結果を削除</button>　

            </form>
            <a href="{% url 'chance:chance' %}" ><button class="form_b_01">Back</button></a>

</div>

<footer>

    <div  class="user_box">
        　　
    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>

</footer>


{% endblock %}

chance/templates/chance/match_detail.html
{% extends 'chance/base.html' %}

{% block content %}
<!--フォームコントロール-->
{% load widget_tweaks %}


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="main_box">
        Match Detail
    </div>

    <div class="mid_box">
        <div class="weak_1">{{ created_date }}</div>
            {{ player }} VS {{ opponent }}

    <hr>
    {{ game_count1 }} - {{ game_count2 }}

    <hr>
    1stサービス成功率：{{ probability_service|floatformat }}%【 {{ all_service }}：{{ all_service_error }} 】<br>
    2ndサービス成功率：{{ probability_second|floatformat }}%【 {{ all_second }}：{{ all_second_error }} 】<br>
    リターン成功率：{{ probability_receive|floatformat }}%【{{ all_receive }}：{{ all_receive_error }}】<br>
    ストローク成功率：{{ probability_stroke|floatformat }}%【{{ all_stroke }}：{{ all_stroke_error }}】<br>
    ネットプレー成功率：{{ probability_net|floatformat }}%【{{ all_net }}：{{ all_net_error }}】<br>
    </div>

    <div class="mid_box">
        <div class="b_box">
            <a href="{% url 'chance:chance' %}" ><button type="submit" class="form_b_01">Back</button></a>
        </div>

        <hr>
        登録内容更新<br><br>

        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.player|add_class:'form_c_01' }}
            {{ form.opponent|add_class:'form_c_01' }}
            {{ form.created_date|add_class:'form_c_01' }}
            <div class="b_box">
            <button type="submit" class="form_b_01">Save</button>
            </div>
        </form>

    </div>
</div>


<footer>

    <div  class="user_box">
        　　
    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>

</footer>


{% endblock %}

chance/templates/chance/match_new.html
{% extends 'chance/base.html' %}

{% block content %}
<!--フォームコントロール-->
{% load widget_tweaks %}

<script type="text/javascript" language="javascript">

    window.onload = function() {
    }

    function onButtonClick1() {
         target = document.getElementById("id_match_id");
         target.value = '0';
    }

    function onButtonClick18() {
         target = document.getElementById("id_shot");
         target.value = '6';
    }
</script>


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="main_box">
        New GAME
    </div>

    <div class="mid_box">
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.player|add_class:'form_c_01' }}
        {{ form.opponent|add_class:'form_c_01' }}
        {{ form.created_date|add_class:'form_c_01' }}
        <div class="b_box">
        <button type="submit" class="form_b_01">Save</button>
        </div>
    </form>
    <br /><br /><br />
    </div>
</div>

<footer>
    <div  class="user_box">

        <div style="text-align:center; font-size:80%; ">
            <div class="weak_5">
             　　
            </div>
        </div>
    </div>
    <div class="copyright"> Copyright © Alpacca System All Rights Reserved.</div>
</footer>

{% endblock %}